### ISSUE TITLE
Statically links CRT in MSVC

### ISSUE THREAD

**Issue by cpowell** [bloomberg/bde#138]
When building via Microsoft Visual Studio in static-library mode, the output is statically linked (/MT) against the C runtime. Unfortunately this conflicts with things that are build to dynamically link against the CRT (/MD), which is possibly/probably the majority of MSVC since (a) that's the default, and (b) that seems to be the general guidance.

That said, this might be not the case when building the BDE libraries with "--library-type shared", but please see the separate issue that "shared" is not currently working in MSVS2013.

**Comment by hyrosen** [comment]
Pinging Chen again...

**Comment by mversche** [comment]
Discussed with Chen. We agree this doesn't make necessarily make sense as a UFID, since it is very windows specific.  I think it would make more sense in the UPLID (platform identifier).

Chen was going to add an additional windows specific configuration option for now.

**Comment by rohanbhindwale** [comment]
Quick update:  Work on this is expected to take place shortly.

**Comment by che2** [comment]
Added ``--msvc-runtime-type`` option to control whether to build using the static or dynamic C run-time library. Change the default to be /MD (dynamic).
