### ISSUE TITLE
bsls_atomic.t test case 7 times out (marked failure) on OS X

### ISSUE THREAD

**Issue by apaprocki** [bloomberg/bde#143]
Machine: Fully patched OS X Yosemite

```
Darwin x.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

Compiler: Xcode 6

```
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

When building in default x64 mode on OS X, all test drivers run successfully except for `bsls_atomic.t` case 7 -- it is cancelled by the test runner for timing out. Running the test manually in `lldb` shows that it is continuously looping performing atomic operations.

I have also tried both with the current code (it selects `bsls_atomicoperations_x64_all_gcc.h` due to the code thinking Clang is GCC 4.4.0) as well as the newer GCC >= 4.7 intrinsics selected when my patch #142 is applied (`bsls_atomicoperations_all_all_gccintrinsics.h`).

Printing out a stack walkback shows that the 2nd and 3rd thread are continuously changing calls, indicating they are not deadlocked, while the 1st thread is stopped in `__semwait_signal`:

```
Process 41142 stopped
* thread #1: tid = 0x235312, 0x00007fff858ef486 libsystem_kernel.dylib`__semwait_signal + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x235343, 0x000000010000cea3 bsls_atomic.t`(anonymous namespace)::PetersonsLockSeqCst<BloombergLP::bsls::AtomicInt>::lock(this=0x00007fff5fbfcc00) + 19 at bsls_atomic.t.cpp:258
  thread #3: tid = 0x235344, 0x000000010000d79c bsls_atomic.t`BloombergLP::bsls::AtomicInt::operator=(this=0x00007fff5fbfcc14, value=1) + 12 at bsls_atomic.h:1070
```

```
Process 54802 stopped
* thread #1: tid = 0x25d8c3, 0x00007fff858ef486 libsystem_kernel.dylib`__semwait_signal + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x25d8e3, 0x000000010000cf5e bsls_atomic.t`(anonymous namespace)::PetersonsLockSeqCst<BloombergLP::bsls::AtomicInt>::lock() + 206
  thread #3: tid = 0x25d8e4, 0x000000010000cf64 bsls_atomic.t`(anonymous namespace)::PetersonsLockSeqCst<BloombergLP::bsls::AtomicInt>::lock() + 212
```

**Comment by rohanbhindwale** [comment]
Created internal ticket # 64653622 for further investigation.

**Comment by rohanbhindwale** [comment]
Split up the test case into two cases.  That should stop the test case from timing out.  

Phabricator review for the code change is at: https://review.openbloomberg.com/D264

**Comment by hyrosen** [comment]
This issue should be closed (I don't have permission to do so myself).
