### ISSUE TITLE
std::unordered_map compilation problem

### ISSUE THREAD

**Issue by FedeGC87** [bloomberg/bde#150]
Hello,

I am working with bde library and I was getting some compilation errors when I included std::unordered_map:

..../bdeExample1.cpp:24:9: error: ‘unordered_map’ in namespace ‘std’ does not name a type

 I have found this code in BDE_BUILD_PATH/include/bsl/unordered_map:

#if 0 // Native STL header disabled until we routinely test for C++11 *libs*
#if defined(BSLS_COMPILERFEATURES_SUPPORT_INCLUDE_NEXT)
#include_next <unordered_map>
#else
#include BSL_NATIVE_CPP_LIB_HEADER(unordered_map)
#endif
#endif

I commented the #if 0/#endif statement and it seems to work fine. Is there any bde library version with this issue fixed? or how could I perform the tests needed to make sure things are working properly?

**Comment by hyrosen** [comment]
The pull request has been applied; see <https://review.openbloomberg.com/D186>.
