### ISSUE TITLE
bde on ARM architecture

### ISSUE THREAD

**Issue by FedeGC87** [bloomberg/bde#152]
waf configuration line:

CCX=/usr/bin/arm-linux-gnueabi-g++-4.7 CC=/usr/bin/arm-linux-gnueabi-gcc-4.7 waf configure --prefix=/home/federico-garciacruz/devel/allocatorBloomberg/bde/build-arm --out=/home/federico-garciacruz/devel/allocatorBloomberg/bde/build-arm -a 32 -t opt_cpp11

output:
Setting top to                           : /home/federico-garciacruz/devel/allocatorBloomberg/bde 
Setting out to                           : /home/federico-garciacruz/devel/allocatorBloomberg/bde/build-arm 
Checking for 'gcc' (c compiler)          : /usr/bin/arm-linux-gnueabi-gcc-4.7 
Checking for 'g++' (c++ compiler)        : /usr/bin/arm-linux-gnueabi-g++-4.7 
os_type                                  : unix 
os_name                                  : linux 
cpu_type                                 : x86_64 
os_ver                                   : 3.13.0 
comp_type                                : gcc 
comp_ver                                 : 4.7.3 
uplid                                    : unix-linux-x86_64-3.13.0-gcc-4.7.3 
ufid                                     : opt_cpp11 
prefix                                   : /home/federico-garciacruz/devel/allocatorBloomberg/bde/build-arm 
Loading BDE metadata                     : ok 
Evaluating options for 'bsl'             : ok 
Evaluating options for 'bdl'             : ok 
Saving configuration                     : ok 
'configure' finished successfully (0.168s)

when I execute waf build I get these errors:

arm-linux-gnueabi-g++-4.7: error: unrecognized command line option ‘-m32’
arm-linux-gnueabi-g++-4.7: error: unrecognized argument in option ‘-march=pentium2’
arm-linux-gnueabi-g++-4.7: note: valid arguments to ‘-march=’ are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m ep9312 iwmmxt iwmmxt2 native
arm-linux-gnueabi-g++-4.7: error: unrecognized argument in option ‘-mtune=opteron’
arm-linux-gnueabi-g++-4.7: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a15 cortex-a5 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale

Am I missing some configuration setting here?

**Comment by gstrauss** [comment]
https://github.com/bloomberg/bde-tools/pull/13

**Comment by gstrauss** [comment]
https://github.com/bloomberg/bde-tools/pull/13 has been merged, adding ARM support to bde-tools repo used to build.

https://github.com/bloomberg/bde/pull/101 and https://github.com/bloomberg/bde/pull/167 add ARM support to bsls_compilerfeatures.h and bsls_platform.h

https://github.com/bloomberg/bde-tools/pull/6 and https://github.com/bloomberg/bde/pull/169 add first-class compiler support for Clang.

We're still waiting for https://github.com/bloomberg/bde/pull/170 to land (@mversche) for bde to use clang compiler intrinsics for atomics, but even so, you should be build bde on ARM now.

@FedeGC87 would you please give bde on ARM another shot?

**Comment by mversche** [comment]
I believe this issue is resolved, so I'm closing (unless we hear otherwise).  Thanks.

**Comment by dgutson** [comment]
We will test it in one of our boards during next week.
Thanks!
