### ISSUE TITLE
links broken on BDE-Allocator-model wiki page

### ISSUE THREAD

**Issue by jdimatteo** [bloomberg/bde#156]
There seem to be many wiki links with "bdl/blob" which stood instead be "bde/blob".

For example, the "BufferedSequentialAllocator" link in section [BDL-Provided bdlma::ManagedAllocator Derived Classes](https://github.com/bloomberg/bde/wiki/BDE-Allocator-model#bdl-provided-bdlmamanagedallocator-derived-classes) links to:

https://github.com/bloomberg/bdl/blob/master/groups/bdl/bdlma/bdlma_bufferedsequentialallocator.h#L210

This link leads to a 404 "Page not found".

It should instead link to:

https://github.com/bloomberg/bde/blob/master/groups/bdl/bdlma/bdlma_bufferedsequentialallocator.h#L210

If you'd like, you can give me privileges to edit the page and I'll fix it myself. (I used to work at Bloomberg if that qualification helps).

**Comment by abeels** [comment]
Reviewed Mike's changes and fixed one last instance.
