### ISSUE TITLE
Several test drivers are using 'deprecated or antiquated headers'

### ISSUE THREAD

**Issue by frutiger** [bloomberg/bde#158]
Test drivers of several components are using a `strstream` which generates this warning with `gcc-4.9.2` on `linux`:

```
/usr/include/c++/4.9.2/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
```

The list of affected test drivers are:

```
bdlt_datetime
bdlt_dayofweekset
bdlt_time
bslma_testallocator
bsls_types
bslstl_stringref
bslx_byteinstream
bslx_byteoutstream
bslx_testinstream
bslx_testoutstream
bslx_typecode
```

It's not clear to me if this is expected/by design, or an oversight.

**Comment by rohanbhindwale** [comment]
Quick update. We plan to begin work on updating our test drivers to not use strstream. However, as Mike mentioned earlier the list of affected files is much larger and the turnaround may take some time.

**Comment by hyrosen** [comment]
I fixed up 50 files which were including the header but not using strstreams.  For the rest, we tend to use strstreams to perform formatted I/O using stack-allocated buffers.  The standards folks who decided to deprecate strstream didn't bother to offer a replacement that can do that, and switching to stringstreams will cause memory allocation to happen, to which our tests may be sensitive.  This rather seems like a bunch of work that isn't worth doing.

**Comment by abeels** [comment]
We're planning on cleaning this up bit-by-bit when people have downtime.  This isn't a high priority, so I wouldn't expect to see progress before late Summer.

**Comment by hyrosen** [comment]
I've updated our internal _bde_ repository to stop using bsl_strstream.h.  Coming soon, the same for _bde-classic_.  The changes will make their way to open source anon.

**Comment by hyrosen** [comment]
The bde-classic changes are done internally as well.
