### ISSUE TITLE
[Windows] Waf error when configuring bde with MinGW

### ISSUE THREAD

**Issue by arkdemon** [bloomberg/bde#173]
Hello everyone.
I have tried configuring BDE with MinGW on Windows 7 32bit.
I use Qt Creator 3.3.2 and its MinGW version 4.9.1

Whenever I use the command 'waf configure --check-c-compiler=gcc and --check-cxx-compiler=g++', (I also tried to modify bde-tools\bin\lib\bdebld\waf\wscript.py - removed 'msvc' and replaced it by 'gcc' and 'g++')

I get the following error: 
Command['C:\\Qt\\Tools\\mingw491_32\\bin\\g++.exe'] returned 1

I looked up the error on the log and the error is said to come from the fact that there are 'no input files'. 
I don't know if it comes from MinGW's g++.exe or if BDE does not support it on Windows.

here is the log (I removed the beginning):

Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['C:\\Programs\\Python-2.7.9\\ ', 'C:\\Programs\\Python-2.7.9\\ Scripts', 'C:\\Programs\\Python-2.7.9\\ Tools\\Scripts', 'C:\\Programs\\Python-2.7.9\\', 'C:\\Qt\\Tools\\mingw491_32\\bin', 'C:\\Programs\\Python-2.7.9\\Scripts', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', ' C:\\Programs\\Git\\cmd', 'C:\\Program Files\\Windows Kits\\8.1\\Windows Performance Toolkit\\', 'C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SDKs\\TypeScript\\1.0\\', 'C:\\Programs\\TortoiseHg\\', 'C:\\Program Files\\CMake\\bin', 'C:\\Programs\\bde-tools\\bin'] var='CC' -> ['C:\\Qt\\Tools\\mingw491_32\\bin\\gcc.exe']
find program=['ar'] paths=['C:\\Programs\\Python-2.7.9\\ ', 'C:\\Programs\\Python-2.7.9\\ Scripts', 'C:\\Programs\\Python-2.7.9\\ Tools\\Scripts', 'C:\\Programs\\Python-2.7.9\\', 'C:\\Qt\\Tools\\mingw491_32\\bin', 'C:\\Programs\\Python-2.7.9\\Scripts', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', ' C:\\Programs\\Git\\cmd', 'C:\\Program Files\\Windows Kits\\8.1\\Windows Performance Toolkit\\', 'C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SDKs\\TypeScript\\1.0\\', 'C:\\Programs\\TortoiseHg\\', 'C:\\Program Files\\CMake\\bin', 'C:\\Programs\\bde-tools\\bin'] var='AR' -> ['C:\\Qt\\Tools\\mingw491_32\\bin\\ar.exe']
C:\Qt\Tools\mingw491_32\bin\gcc.exe

Checking for 'g++' (C++ compiler)
find program=['g++', 'c++'] paths=['C:\\Programs\\Python-2.7.9\\ ', 'C:\\Programs\\Python-2.7.9\\ Scripts', 'C:\\Programs\\Python-2.7.9\\ Tools\\Scripts', 'C:\\Programs\\Python-2.7.9\\', 'C:\\Qt\\Tools\\mingw491_32\\bin', 'C:\\Programs\\Python-2.7.9\\Scripts', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v6.0\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', ' C:\\Programs\\Git\\cmd', 'C:\\Program Files\\Windows Kits\\8.1\\Windows Performance Toolkit\\', 'C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SDKs\\TypeScript\\1.0\\', 'C:\\Programs\\TortoiseHg\\', 'C:\\Program Files\\CMake\\bin', 'C:\\Programs\\bde-tools\\bin'] var='CXX' -> ['C:\\Qt\\Tools\\mingw491_32\\bin\\g++.exe']
(tool ar is already loaded, skipping)
C:\Qt\Tools\mingw491_32\bin\g++.exe
['C:\\Qt\\Tools\\mingw491_32\\bin\\g++.exe']
err: g++.exe: fatal error: no input files

compilation terminated.

**Comment by mversche** [comment]
Visual studio is the supported compiler on windows (https://github.com/bloomberg/bde/wiki/Supported-Platforms).  @che2 might be able to point you to the right way to configure `waf` to pick up your compiler (I think he's tried gcc with cygwin, which is probably similar), but even if he did, gcc/windows is not a configuration we build/test.

**Comment by che2** [comment]
@arkdemon, sorry MinGW is not supported, we haven't tested building BDE on this platform. I recommend that you try building BDE Visual Studio, which is supported. You can find instructions at
http://bloomberg.github.io/bde-tools/tutorials.html#use-bde-setwafenv-py-to-build-bde-on-windows.
