### ISSUE TITLE
Wiki has old Coding Standards Document

### ISSUE THREAD

**Issue by pkumar0508** [bloomberg/bde#188]
https://github.com/bloomberg/bde/wiki/Introduction-to-BDE-Coding-Standards
The Coding Standards Document link leads to the 2012.11.07 version of the coding standards.
I think the latest version of the BDE coding standards is 2015.07.07.

Could you please update the Document to the latest version?
I would submit a pull request, but I don't know how to fork/clone the Wiki repository (in CORP):
https://github.com/bloomberg/bde.wiki.git

**Comment by che2** [comment]
Updated the coding standards document to the latest version.
