### ISSUE TITLE
Circular dependecy bdlt<->bdls

### ISSUE THREAD

**Issue by DavidKeller** [bloomberg/bde#209]
Hi,

```
$waf build --test build
[...]
[1664/2610] Compiling groups/bdl/bdlt/bdlt_timeutil.t.cpp
[bdlt_timeutil.t.cpp (ERROR)] <<<<<<<<<<
../groups/bdl/bdlt/bdlt_timeutil.t.cpp:4:27: fatal error: bdls_testutil.h: No such file or directory
compilation terminated.
>>>>>>>>>>
```

So **bdlt** depends on **bdls** _but_ it's not declared in its dep file:
```
$cat bdlt.dep
bdlb
bdlc
bdlscm
```

As **bdls** uses **bdlt**, we have an hidden circular dependency:
```
$cat bdls.dep
bdlde
bdlf
bdlsb
bdlscm
bdlt
```

**bdls_testutil** seems deprecated, is **bslim_testutil** the replacement ?

**Comment by mversche** [comment]
Yes, the branch that landed `bdlt_time` on thursday was in-flight when the `testutil` component was moved.  Not sure why this isn't in the master nightlies...

**Comment by DavidKeller** [comment]
I'have a fix that replace **bdls_testutil** with **bslim_testutil** on **bdlt_timeutil.t.cpp**.

Should I request a merge ?

**Comment by mversche** [comment]
That isn't what I meant (I had guessed there might be something wrong with our nightly build configuration).  You are correct about the situation though. It was fixed locally last week.  We'll update github today.  Don't need a pull-request.

**Comment by DavidKeller** [comment]
Okay great. Thank you.
