### ISSUE TITLE
Mentions of BLP license

### ISSUE THREAD

**Issue by jlaire** [bloomberg/bde#215]
These files contain the closed source epilogue in the middle (multiple times, grep for "All Rights Reserved"):

```
groups/bal/balber/balber_berdecoder.t.cpp
groups/bal/balber/balber_berencoder.t.cpp
groups/bal/balber/balber_beruniversaltagnumber.t.cpp
groups/bal/balxml/balxml_decoder.t.cpp
```

I think they should be removed to avoid confusion. The files contain the open source epilogue in the end.

**Comment by sbreitstein** [comment]
Internal ticket DRQS 84377086 has been created to track this issue.

**Comment by hyrosen** [comment]
Internal pull request https://bbgithub.dev.bloomberg.com/bde/bde/pull/504 written to fix this issue.

**Comment by mversche** [comment]
The fix for this is on `master`
