### ISSUE TITLE
Publish benchmark source code for N4468 and update notes

### ISSUE THREAD

**Issue by alex-weej** [bloomberg/bde#216]
In `benchmarks/allocators`, there is a comment:

> 2015-04-29 The benchmark source code for N4468 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4468.pdf) is currently being packaged for publication.

It's been 15 months since this log date, is this still "being packaged"?

**Comment by abeels** [comment]
The benchmark source code for all three papers ([N4468](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4468.pdf) and its two revisions [P0089R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0089r0.pdf) and [P0089R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0089r1.pdf)) is published at [bde-allocator-benchmarks](https://github.com/bloomberg/bde-allocator-benchmarks/tree/master/benchmarks/allocators).

In addition, Graham Bleaney has written a paper (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0213r0.pdf) validating the results of P0089R0.

**Comment by alex-weej** [comment]
This was the file to which I was referring: https://github.com/bloomberg/bde/tree/af21cbecb6bf2a1ace42bf6ac3c106d4e2d26ed3/benchmarks/allocators

**Comment by abeels** [comment]
Updated.  Thanks for pointing out the discrepancy.
