### ISSUE TITLE
waf build --test build does not work

### ISSUE THREAD

**Issue by avysotsk** [bloomberg/bde#217]
$ waf configure
Setting top to                           : /tmp/bde
Setting out to                           : /tmp/bde/build
Checking for 'gcc' (C compiler)          : /bin/gcc
Checking for 'g++' (C++ compiler)        : /bin/g++
Prefix                                   : /usr/local
Uplid                                    : unix-linux-x86_64-3.10.0-gcc-4.8.5
Ufid                                     : dbg_exc_mt_64_cpp11
Loading btl                              : ok
Loading bsl                              : ok
Loading bal                              : ok
Loading bbl                              : ok
Loading bdl                              : ok
Loading inteldfp                         : ok
Loading pcre2                            : ok
Loading decnumber                        : ok
Using default option rules from          : /tmp/bde-tools/etc/default.opts
Configured package groups                : bal bbl bdl bsl btl
Configured third-party packages          : decnumber inteldfp pcre2
Use flat include directory               : no
Lib install directory                    : lib
Pkg-config install directory             : lib/pkgconfig
# UORs, inner packages, and components   : 8 48 801
'configure' finished successfully (0.130s)
$ waf build 
//It works OK
$ waf build --test build
//Here it failed during compilation of ../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp
$  /bin/g++ -Wcast-align -Wcast-qual -Wall -Wextra -Wformat-security -Wformat-y2k -Winit-self -Wno-long-long -Wno-unknown-pragmas -Wpacked -Wpointer-arith -Wwrite-strings -Wno-unused-value -Wno-char-subscripts -Wsign-compare -Wparentheses -Wlogical-op -Wstrict-overflow -Wvla -Wvolatile-register-var -fdiagnostics-show-option -Wno-sign-conversion -Wconversion -Waddress -Wtype-limits -Wcast-align -Wsign-compare -Wformat -Woverflow -Wlarger-than-100000 -Werror=cast-qual -m64 -mtune=opteron -fPIC -DBDE_BUILD_TARGET_DBG -DBDE_BUILD_TARGET_EXC -DBDE_BUILD_TARGET_MT -DBDE_BUILD_TARGET_CPP11 -std=c++11 --param ggc-min-expand=30 -fexceptions -g -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -DBSLS_IDENT_OFF -DBDE_NO_CPP_STDLIB -I/tmp/bde/groups/bsl/bslalg -I/tmp/bde/groups/bsl/bsltf -I/tmp/bde/groups/bsl/bslma -I/tmp/bde/groups/bsl/bslmf -I/tmp/bde/groups/bsl/bslscm -I/tmp/bde/groups/bsl/bsls ../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp -c -o /tmp/bde/build/groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp.1.

../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp:1377:32: error: 'bslma_Allocator' has not been declared
                                bslma_Allocator      *alloc,
                                ^
../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp: In constructor 'ConstructTestTypeAllocArgT::ConstructTestTypeAllocArgT(bsl::allocator_arg_t, int*, ConstructTestTypeAllocArgT::Arg1, ConstructTestTypeAllocArgT::Arg2, ConstructTestTypeAllocArgT::Arg3, ConstructTestTypeAllocArgT::Arg4, ConstructTestTypeAllocArgT::Arg5, ConstructTestTypeAllocArgT::Arg6, ConstructTestTypeAllocArgT::Arg7, ConstructTestTypeAllocArgT::Arg8, ConstructTestTypeAllocArgT::Arg9, ConstructTestTypeAllocArgT::Arg10, ConstructTestTypeAllocArgT::Arg11, ConstructTestTypeAllocArgT::Arg12, ConstructTestTypeAllocArgT::Arg13, ConstructTestTypeAllocArgT::Arg14)':
../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp:1386:32: error: cannot convert 'int*' to 'BloombergLP::bslma::Allocator*' in initialization
         , d_a13(a13), d_a14(a14) {}
                                ^
In file included from ../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp:3:0:
/tmp/bde/groups/bsl/bslalg/bslalg_scalarprimitives.h: In instantiation of 'static void BloombergLP::bslalg::ScalarPrimitives_Imp::construct(TARGET_TYPE*, BloombergLP::bslma::Allocator*, bsl::integral_constant<int, 6>*) [with TARGET_TYPE = ConstructTestTypeAllocArgT]':
/tmp/bde/groups/bsl/bslalg/bslalg_scalarprimitives.h:1758:60:   required from 'static void BloombergLP::bslalg::ScalarPrimitives::construct(TARGET_TYPE*, BloombergLP::bslma::Allocator*) [with TARGET_TYPE = ConstructTestTypeAllocArgT]'
../groups/bsl/bslalg/bslalg_scalarprimitives.t.cpp:2007:9:   required from here
/tmp/bde/groups/bsl/bslalg/bslalg_scalarprimitives.h:2985:5: error: no matching function for call to 'ConstructTestTypeAllocArgT::ConstructTestTypeAllocArgT(const bsl::allocator_arg_t&, BloombergLP::bslma::Allocator*&)'
     ::new (address) TARGET_TYPE(bsl::allocator_arg, allocator);

**Comment by mversche** [comment]
Yes - it appears the use of a deprecated type name for `bslma::Allocator` (`bslma_Allocator`) is being used.  Will try and push a fix tonight

**Comment by mversche** [comment]
Should be fixed.
