### ISSUE TITLE
Error compiling balst_stacktraceresolverimpl_windows.cpp on VS2015

### ISSUE THREAD

**Issue by bcamel** [bloomberg/bde#219]
I am using Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x86.
Compiling the file `balst_stacktraceresolverimpl_windows.cpp` yields the following error (shortened for readability):

`balst_stacktraceresolverimpl_windows.cpp(79): error
C2664: 'void BloombergLP::bsls::Log::logFormattedMessage(BloombergLP::bsls::LogSeverity::Enum,const char *,int,const char *,...)': cannot convert argument 1 from 'const char [7]' to BloombergLP::bsls::LogSeverity::Enum'` 
`balst_stacktraceresolverimpl_windows.cpp(79): note: There is no context in which this conversion is possible`

I believe, line 79 of said file should be changed from 

`        BSLS_LOG("%s: %d", string, static_cast<int>(lastError));`

to

`        BSLS_LOG_ERROR("%s: %d", string, static_cast<int>(lastError));`.

**Comment by mversche** [comment]
Indeed.  Have a fix, will push an update with that fix today.

**Comment by mversche** [comment]
Fixed on master
