### ISSUE TITLE
error in groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h

### ISSUE THREAD

**Issue by avysotsk** [bloomberg/bde#222]
Compilation of bslmf_memberfunctionpointertraits.cpp failes with error:
$ CC -library=stlport4 -DBDE_BUILD_TARGET_STLPORT -template=no%extdef -xcode=pic32 -m64 -xtarget=generic -DBDE_BUILD_TARGET_EXC -DBDE_BUILD_TARGET_MT -DBDE_BUILD_TARGET_OPT -xtarget=generic -xthreadvar=dynamic -xannotate=no -features=except -xO3 -DNDEBUG -xbuiltin=%all -D_POSIX_PTHREAD_SEMANTICS -mt -DBSLS_IDENT_OFF -DBDE_NO_CPP_STDLIB -DPIC -I/bde/groups/bsl/bslmf -I/bde/groups/bsl/bslscm -I/bde/groups/bsl/bsls ../groups/bsl/bslmf/bslmf_memberfunctionpointertraits.cpp -c -o /bde/build/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.cpp.1.o

"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 265: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 265: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 265: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 265: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 292: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 292: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 292: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 292: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 321: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 321: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 321: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 321: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 356: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 356: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 356: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 356: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 397: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 397: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 397: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 397: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 444: Error: bslmf_Tag is not defined.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 444: Error: A declaration does not specify a tag or an identifier.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 444: Error: Use ";" to terminate declarations.
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 444: Error: "}" expected instead of "<".
"/bde/groups/bsl/bslmf/bslmf_memberfunctionpointertraits.h", line 497: Error: bslmf_Tag is not defined.

Changing "bslmf_Tag" to "bslmf::Tag" in bslmf_memberfunctionpointertraits.h file will solve the problem. 
For example:
WAS >      typedef bslmf_Tag<0> NonCVTag;    // non-const, non-volatile member func
NEW <     typedef bslmf::Tag<0> NonCVTag;    // non-const, non-volatile member func

**Comment by abeels** [comment]
Resolved with 6bd284f2589ad10e3b99b55c40a34c43807d3fbc.
