### ISSUE TITLE
Support for modern Sun compiler in bslalg_dequeiterator.h file

### ISSUE THREAD

**Issue by avysotsk** [bloomberg/bde#223]
Using modern Sun compilers leads to the compilation failure on, for example, file bslalg_dequeiterator.cpp.
$ CC -library=stlport4 -DBDE_BUILD_TARGET_STLPORT -template=no%extdef -xcode=pic32 -m64 -xtarget=generic -DBDE_BUILD_TARGET_EXC -DBDE_BUILD_TARGET_MT -DBDE_BUILD_TARGET_OPT -m64 -xtarget=generic -xthreadvar=dynamic -xannotate=no -features=except -xO3 -DNDEBUG -xbuiltin=%all -D_POSIX_PTHREAD_SEMANTICS -mt -DBSLS_IDENT_OFF -DBDE_NO_CPP_STDLIB -library=no%rwtools7 -xcode=pic32 -DPIC -I/bde/groups/bsl/bslalg -I/bde/groups/bsl/bsltf -I/bde/groups/bsl/bslma -I/bde/groups/bsl/bslmf -I/bde/groups/bsl/bslscm -I/bde/groups/bsl/bsls ../groups/bsl/bslalg/bslalg_dequeiterator.cpp -c -o /bde/build/groups/bsl/bslalg/bslalg_dequeiterator.cpp.1.o
CC: Warning: illegal use of -library option, illegal item ignored: rwtools7
CC: Warning: illegal use of -library option, empty value ignored
"/bde/groups/bsl/bslalg/bslalg_dequeiterator.h", line 318: Error: Template parameter "VALUE_TYPE" may not be redeclared in this scope.
"/bde/groups/bsl/bslalg/bslalg_dequeiterator.h", line 322: Error: Template parameter "VALUE_TYPE" may not be redeclared in this scope.
"/bde/groups/bsl/bslalg/bslalg_dequeiterator.h", line 326: Error: Template parameter "VALUE_TYPE" may not be redeclared in this scope.

The solution is to change the line 312 of file groups/bsl/bslalg/bslalg_dequeiterator.h from 
#ifdef BSLS_PLATFORM_CMP_SUN
to 
#if defined( BSLS_PLATFORM_CMP_SUN ) && BSLS_PLATFORM_CMP_VER_MAJOR < 0x5130

This makes old Sun compilers to use the "old style" declaration, but modern Sun compilers to use another declaration previously accepted by xlC, gcc and windows, but not Sun.

**Comment by mversche** [comment]
Could you confirm the modern version of Sun Studio you are using?

**Comment by avysotsk** [comment]
$ CC -V
CC: Studio 12.5 Sun C++ 5.14 SunOS_sparc 2016/05/31

I believe it is Oracle Developer Studio 12.5 - http://www.oracle.com/technetwork/server-storage/developerstudio/downloads/index.html

**Comment by AlisdairM** [comment]
Looking at making these operators friend functions, defined inline, rather than trying to befriend a function template.  This should work for all compilers, eliminating the version check and workaround entirely.

**Comment by AlisdairM** [comment]
I believe the patch for this issue has landed.

**Comment by avysotsk** [comment]
Yes. The issue is fixed. Verified.

**Comment by mversche** [comment]
Sounds good.  Thanks
