### ISSUE TITLE
Compile error: 'memcpy' is not a member of 'bsl'

### ISSUE THREAD

**Issue by yujiezha** [bloomberg/bde#229]
Compile failed for both
 groups/bal/balst/balst_stacktraceresolverimpl_elf.cpp
 groups/bal/balst/balst_stacktraceresolver_dwarfreader.cpp

saw bsl_cstring.h is included in both files, maybe missing some other include files (verified that my env has std::memcpy)

In file included from ../groups/bal/balst/balst_stacktraceresolver_dwarfreader.c               pp:3:0:
/projects/bde/groups/bal/balst/balst_stacktraceresolver_dwarfreader.h               : In member function 'int BloombergLP::balst::StackTraceResolver_DwarfReader::re               adValue(TYPE*)':
/projects/bde/groups/bal/balst/balst_stacktraceresolver_dwarfreader.h               :462:5: error: 'memcpy' is not a member of 'bsl'
     bsl::memcpy(dst, d_readPtr, sizeof(*dst));
     ^

In file included from ../groups/bal/balst/balst_stacktraceresolverimpl_elf.cpp:1               9:0:
/projects/bde/groups/bal/balst/balst_stacktraceresolver_dwarfreader.h               : In member function 'int BloombergLP::balst::StackTraceResolver_DwarfReader::re               adValue(TYPE*)':
/projects/bde/groups/bal/balst/balst_stacktraceresolver_dwarfreader.h               :462:5: error: 'memcpy' is not a member of 'bsl'
     bsl::memcpy(dst, d_readPtr, sizeof(*dst));
     ^

**Comment by abeels** [comment]
This should be fixed by c3119119653af6dd17912f0f57e46a870b7fcec6
