### ISSUE TITLE
intel-decimal wrapper using only official c++ stl

### ISSUE THREAD

**Issue by tmawork** [bloomberg/bde#235]
Hello,

we'd like to use the decimal-wrapper for the intel lib (bdldfp); but would prefer
to use only official stl includes for that.
Is there / has there been a branch which might support this? If not, suggestions and hints
if there would be any problems to consider when attempting to adapt to the (c++2003) STL would be appreciated.
(Reason: For our project we would like to only have a minimal dependency on additional code because
we might need to make adaptions for various target platforms and their quirky compilers).

**Comment by mversche** [comment]
Sorry - we will not pursue this.  Re-engineering `bdldfp` to use the platform's standard library is not in keeping with the sort of integrated solution the BDE libraries seek to provide.  It also would surely break all sorts of backwards compatibility for us.

I understand the reticence for the additional dependencies. I'd note that BDE supports a fairly wide set of compilers (though obviously you may use ones we do not support).
