### ISSUE TITLE
references to internal tools

### ISSUE THREAD

**Issue by austo** [bloomberg/bde#253]
should [this](https://github.com/bloomberg/bde/blob/master/groups/bal/baljsn/baljsn_encoder.h#L86) be in the OSS documentation?

[bbgithub profile](https://bbgithub.dev.bloomberg.com/amoran24)

**Comment by osubboo** [comment]
Internal BDE code is completely synchronized with the open source version and there are no mechanisms to do conditional code manipulations ( this proven to be error-prone and labor intensive ). BDE team will try to limit the references to the internal tools where not needed.
