### ISSUE TITLE
crazy #undef

### ISSUE THREAD

**Issue by seanbaxter** [bloomberg/bde#255]
bde/groups/bsl/bsls/bsls_libraryfeatures.h:1152:77

#undef BSLS_LIBRARYFEATURES_HAS_CPP11_PAIR_PIECEWISE_CONSTRUCTOR  1

Breaks my compiler. Is this supposed to be an #undef without the 1 or a #define? What you have now is illegal syntax.

**Comment by notadragon** [comment]
> bde/groups/bsl/bsls/bsls_libraryfeatures.h:1152:77
> 
> #undef BSLS_LIBRARYFEATURES_HAS_CPP11_PAIR_PIECEWISE_CONSTRUCTOR 1
> 
> Breaks my compiler. Is this supposed to be an #undef without the 1 or a #define? What you have now is illegal syntax.

I would be curious why you are attempting to parse this line.. it's in a block guarded for a beta Sun compiler (and specifically a version of that compiler which even we are not using yet).   I'm not saying it would work on that compiler - just that only a compiler where BSLS_PLATFORM_CMP_SUN gets defined and BSLS_PLATFORM_CMP_VERSION >= 0x5150 is true should this be considered ill-formed.

**Comment by osubboo** [comment]
The fix is merged into the internal base. Will be synced within an hour.

**Comment by seanbaxter** [comment]
It's ill-formed no matter what the macros are. 

I'm tokenizing those lines because my first pass breaks the text into a tree of nodes. Each node is either an uninterrupted block of text or a directive. #if/ifdef directive nodes have children. This lets me perform preprocessor control flow by navigating a tree or directives rather than having to read text. Macro include guards and the like are trivially captured by this structure.

The values of macros are used when traversing the tree to emit C++ tokens (as opposed to PP tokens). The BSLS_PLATFORM_CMP_SUN prevents the compiler from executing that directive, not from parsing it.

**Comment by notadragon** [comment]
Nope, that line is not a valid control-line (it does not match any of the productions in [cpp.pre]/1), but that just makes it a text-line part of the group under the #ifdef.  The group is skipped, so nothing is ill-formed just because that line is not parsable as anything useful.

That bit of functionality is important in case future standards or conforming compiler extensions on other compilers add meaning to such a directive.

**Comment by hyrosen** [comment]
It's not a text line:
A sequence of preprocessing tokens is only a text-line if it does not begin with a directive-introducing token.

However:
When in a group that is skipped ([cpp.cond]), the directive syntax is relaxed to allow any sequence of preprocessing tokens to occur between the directive name and the following new-line character.

**Comment by RMGiroux** [comment]
Whether or not circle should have ignored them, we're still grateful you found them - those lines were just silly.

They're fixed now, and the fix has propagated to github.  Thanks!
