### ISSUE TITLE
fix __LINE__ issues

### ISSUE THREAD

**Issue by seanbaxter** [bloomberg/bde#265]
https://github.com/bloomberg/bde/pull/262

I'd like the problem described here resolved for all affected tests. It's one of the few things remaining preventing my compiler from hitting 100% test compliance. Thanks.

**Comment by cppguru** [comment]
bslmt_readerwriterlockassert.t.cpp
   bdls_testutil.t.cpp
   ball_log.t.cpp
   ball_logthrottle.t.cpp
   bael_log.t.cpp

are going to be addressed by me in a separate pull request.  Alisdair in the meantime will either fix the remaining "old style" names or not in #262, it is up to him, as I have looked at the whole file and it already has both style. :(  Which means this change set did not introduce an inconsistency.

**Comment by seanbaxter** [comment]
Works! thx.
