### ISSUE TITLE
unreachable URL at README; https://bde.bloomberg.com/bde/library_information/build.html

### ISSUE THREAD

**Issue by koalalovepenguin** [bloomberg/bde#293]
https://bde.bloomberg.com/bde/library_information/build.html

is not reachable

as a request for a casual check, I submit this issue

hope this is appropriate channel (I wonder I should have used the DRQS channel; if it was, please forgive my lack of knowledge and delete this issue

always such a big fan for the project

**Comment by RMGiroux** [comment]
Thanks @koalalovepenguin - this is the correct channel.

Where did you see this URL, please?

**Comment by RMGiroux** [comment]
If you're referring to the links in the "Internal" sections of the README.md file, that's deliberate.  Those sections are intended only for use inside the Bloomberg development environment.

**Comment by koalalovepenguin** [comment]
I meant the internal section; I did not know that it was for the internal users only. thank you for the swift answer and sorry to bother. I will close the issue.

always a big fan; thank you for the good work!
