### ISSUE TITLE
Conan support

### ISSUE THREAD

**Issue by Elnee** [bloomberg/bde#299]
I've found the `conanfile.py` in the repo. But it seems to be very raw and not workable. Would be very nice to have a Conan recipe for the library. Is it planned to be implemented? Thanks.

**Comment by osubboo** [comment]
The conan recipe added clearly states that it is for internal use only ( and it hides the recipe implementation ).
We might at some point look into providing a functioning OSS recipe, but it  is not a priority right now.

**Comment by Elnee** [comment]
@osubboo Thank you for quick response. I've just tried to use `rmqcpp` and find out that it's depended on `bsl` headers. But it's not related to the topic... 

Have a nice time ☺️
